Repository si-2019/SI-FRONTEND, pull requests merged in 2019-04, with the labels that each got.

#21 Sprint #1 - Kao-student-imam-mogucnost-odabira-projekta-iz-liste-postojecih-kako-bi-imao-uvid-u-zadatke-istog
  reactapp/package-lock.json
  reactapp/package.json
  reactapp/src/App.js
  reactapp/src/components/PregledZadatakaProjekta/PregledZadatakaProjekataAcceptance.test.js
  reactapp/src/components/PregledZadatakaProjekta/PregledZadatakaProjekta.js
  reactapp/src/components/PregledZadatakaProjekta/PregledZadatakaProjekta.test.js
Labels: MIKE, Pushed

#26 Kao student imam mogućnost prikaza liste zadataka odabranog projekta kako bih imao pregled kreiranih zadataka
  README.md
  reactapp/src/App.js
  reactapp/src/components/PregledListeProjekata/PregledListeProjekata.js
  reactapp/src/components/PregledListeProjekata/PregledListeProjekataAcceptance.test.js
  reactapp/src/react-app-env.d.ts
  reactapp/tsconfig.json
Labels: Ready4Review

#48 Us 49 fox: prikazuje danasnji dan i datum na pocetnoj stranici
  reactapp/src/App.js
  reactapp/src/danDatum.js
Labels: FOX

#68 Dodan link na naziv grupa
  reactapp/src/FOX/Predmet.js
Labels: FOX, Ready4Review

#58 Sprint#1 - Kao student ima mogućnost pristupa formi za unos informacija vezanih za projekat
  reactapp/package-lock.json
  reactapp/src/App.css
  reactapp/src/App.js
  reactapp/src/UnosInformacija.js
Labels: Ready4Review

#57 SPRINT #1-Kao student imam mogućnost prikaza liste predmeta kako bih mogao odabrati jedan za koji želim kreirati projektnu grupu
  reactapp/package-lock.json
  reactapp/package.json
  reactapp/src/App.css
  reactapp/src/App.js
  reactapp/src/__snapshots__/prikazListe.test.js.snap
  reactapp/src/prikazListe.js
  reactapp/src/prikazListe.test.js
Labels: Ready4Review

#69 Dodan link Raspored u navigaciji
  reactapp/src/FOX/Header.js
  reactapp/src/FOX/Navbar001.js
Labels: FOX, Ready4Review

#81 Ispravljena greska branch FOX_US58
  reactapp/src/FOX/Navbar001.js
Labels: FOX

#83 Fox_US26
  reactapp/.gitignore
  reactapp/src/FOX/Navbar001.js
Labels: FOX, Ready4Review
